PERMISSIONS = { 
	 "android.permission.SEND_SMS" : ["dangerous", "Used for permissions that allow an application to send messages receiving or reading an MMS. Allows an application to send SMS messages."], 
	 "android.permission.SEND_RESPOND_VIA_MESSAGE" : ["signature|system", "Allows an application (Phone) to send a request to other applications Not for use by third-party applications."], 
	 "android.permission.RECEIVE_SMS" : ["dangerous", "Allows an application to monitor incoming SMS messages, to record or perform processing on them."], 
	 "android.permission.RECEIVE_MMS" : ["dangerous", "Allows an application to monitor incoming MMS messages, to record or perform processing on them."], 
	 "android.permission.RECEIVE_EMERGENCY_BROADCAST" : ["signature|system", "Allows an application to receive emergency cell broadcast messages,  Pending API council approval"], 
	 "android.permission.READ_CELL_BROADCASTS" : ["dangerous", "Allows an application to read previously received cell broadcast  Pending API council approval"], 
	 "android.permission.READ_SMS" : ["dangerous", "Allows an application to read SMS messages."], 
	 "android.permission.WRITE_SMS" : ["dangerous", "Allows an application to write SMS messages."], 
	 "android.permission.RECEIVE_WAP_PUSH" : ["dangerous", "Allows an application to monitor incoming WAP push messages."], 
	 "android.permission.READ_CONTACTS" : ["dangerous", "Used for permissions that provide access to the user's social connections, expressed as two distinct permissions). Allows an application to read the user's contacts data."], 
	 "android.permission.WRITE_CONTACTS" : ["dangerous", "Allows an application to write (but not read) the user's contacts data."], 
	 "android.permission.BIND_DIRECTORY_SEARCH" : ["signature|system", "Allows an application to execute contacts directory search. Not for use by third-party applications."], 
	 "android.permission.READ_CALL_LOG" : ["dangerous", "Allows an application to read the user's call log. targetSdkVersion}</a> is 16 or higher.</p>"], 
	 "android.permission.WRITE_CALL_LOG" : ["dangerous", "Allows an application to write (but not read) the user's targetSdkVersion}</a> is 16 or higher.</p>"], 
	 "android.permission.READ_SOCIAL_STREAM" : ["dangerous", "Allows an application to read from the user's social stream."], 
	 "android.permission.WRITE_SOCIAL_STREAM" : ["dangerous", "Allows an application to write (but not read) the user's social stream data."], 
	 "android.permission.READ_PROFILE" : ["dangerous", "Used for permissions that provide access to information about the device distinct permissions). Allows an application to read the user's personal profile data."], 
	 "android.permission.WRITE_PROFILE" : ["dangerous", "Allows an application to write (but not read) the user's personal profile data."], 
	 "android.permission.READ_CALENDAR" : ["dangerous", "Used for permissions that provide access to the device calendar to create / view events. Allows an application to read the user's calendar data."], 
	 "android.permission.WRITE_CALENDAR" : ["dangerous", "Allows an application to write (but not read) the user's calendar data."], 
	 "android.permission.READ_USER_DICTIONARY" : ["dangerous", "Used for permissions that provide access to the user calendar to create / view events. Allows an application to read the user dictionary. This should the Settings app."], 
	 "android.permission.WRITE_USER_DICTIONARY" : ["normal", "Used for permissions that provide access to the user calendar to create / view events. Allows an application to write to the user dictionary."], 
	 "com.android.browser.permission.READ_HISTORY_BOOKMARKS" : ["dangerous", "Used for permissions that provide access to the user bookmarks and browser history. Allows an application to read (but not write) the user's browsing history and bookmarks."], 
	 "com.android.browser.permission.WRITE_HISTORY_BOOKMARKS" : ["dangerous", "Allows an application to write (but not read) the user's browsing history and bookmarks."], 
	 "com.android.alarm.permission.SET_ALARM" : ["normal", "Used for permissions that provide access to the user voicemail box. Allows an application to broadcast an Intent to set an alarm for the user."], 
	 "com.android.voicemail.permission.ADD_VOICEMAIL" : ["dangerous", "Used for permissions that provide access to the user voicemail box. Allows an application to add voicemails into the system."], 
	 "android.permission.ACCESS_FINE_LOCATION" : ["dangerous", "Used for permissions that allow access to the user's current location. Allows an app to access precise location from location sources such as GPS, cell towers, and Wi-Fi."], 
	 "android.permission.ACCESS_COARSE_LOCATION" : ["dangerous", "Allows an app to access approximate location derived from network location sources such as cell towers and Wi-Fi."], 
	 "android.permission.ACCESS_MOCK_LOCATION" : ["dangerous", "Allows an application to create mock location providers for testing"], 
	 "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" : ["normal", "Allows an application to access extra location provider commands"], 
	 "android.permission.INSTALL_LOCATION_PROVIDER" : ["signature|system", "Allows an application to install a location provider into the Location Manager. Not for use by third-party applications."], 
	 "android.permission.LOCATION_HARDWARE" : ["signature|system", "Allows an application to use location features in hardware, Not for use by third-party applications."], 
	 "android.permission.INTERNET" : ["dangerous", "Used for permissions that provide access to networking services.  The or other related network operations. Allows applications to open network sockets."], 
	 "android.permission.ACCESS_NETWORK_STATE" : ["normal", "Allows applications to access information about networks"], 
	 "android.permission.ACCESS_WIFI_STATE" : ["normal", "Allows applications to access information about Wi-Fi networks"], 
	 "android.permission.CHANGE_WIFI_STATE" : ["dangerous", "Allows applications to change Wi-Fi connectivity state"], 
	 "android.permission.ACCESS_WIMAX_STATE" : ["normal", ""], 
	 "android.permission.CHANGE_WIMAX_STATE" : ["dangerous", ""], 
	 "android.permission.BLUETOOTH" : ["dangerous", "Used for permissions that provide access to other devices through Bluetooth. Allows applications to connect to paired bluetooth devices"], 
	 "android.permission.BLUETOOTH_ADMIN" : ["dangerous", "Allows applications to discover and pair bluetooth devices"], 
	 "android.permission.BLUETOOTH_PRIVILEGED" : ["system|signature", "Allows applications to pair bluetooth devices without user interaction. This is not available to third party applications."], 
	 "android.permission.BLUETOOTH_STACK" : ["signature", "Allows bluetooth stack to access files"], 
	 "android.permission.NFC" : ["dangerous", "Allows applications to perform I/O operations over NFC"], 
	 "android.permission.CONNECTIVITY_INTERNAL" : ["signature|system", "Allows an internal user to use privileged ConnectivityManager APIs."], 
	 "android.permission.RECEIVE_DATA_ACTIVITY_CHANGE" : ["signature|system", ""], 
	 "android.permission.LOOP_RADIO" : ["signature|system", "Allows access to the loop radio (Android@Home mesh network) device."], 
	 "android.permission.GET_ACCOUNTS" : ["normal", "Permissions for direct access to the accounts managed by the Account Manager. Allows access to the list of accounts in the Accounts Service"], 
	 "android.permission.AUTHENTICATE_ACCOUNTS" : ["dangerous", "Allows an application to act as an AccountAuthenticator for the AccountManager"], 
	 "android.permission.USE_CREDENTIALS" : ["dangerous", "Allows an application to request authtokens from the AccountManager"], 
	 "android.permission.MANAGE_ACCOUNTS" : ["dangerous", "Allows an application to manage the list of accounts in the AccountManager"], 
	 "android.permission.ACCOUNT_MANAGER" : ["signature", "Allows applications to call into AccountAuthenticators. Not for use by third-party applications."], 
	 "android.permission.CHANGE_WIFI_MULTICAST_STATE" : ["dangerous", "Used for permissions that provide direct access to the hardware on flashlight,  etc. Allows applications to enter Wi-Fi Multicast mode"], 
	 "android.permission.VIBRATE" : ["normal", "Allows access to the vibrator"], 
	 "android.permission.FLASHLIGHT" : ["normal", "Allows access to the flashlight"], 
	 "android.permission.WAKE_LOCK" : ["normal", "Allows using PowerManager WakeLocks to keep processor from sleeping or screen from dimming"], 
	 "android.permission.TRANSMIT_IR" : ["normal", "Allows using the device's IR transmitter, if available"], 
	 "android.permission.MODIFY_AUDIO_SETTINGS" : ["normal", "Used for permissions that provide direct access to speaker settings the device. Allows an application to modify global audio settings"], 
	 "android.permission.MANAGE_USB" : ["signature|system", "Used for permissions that provide direct access to the hardware on the device.  This includes audio, the camera, vibrator, etc. Allows an application to manage preferences and permissions for USB devices"], 
	 "android.permission.ACCESS_MTP" : ["signature|system", "Allows an application to access the MTP USB kernel driver."], 
	 "android.permission.HARDWARE_TEST" : ["signature", "Allows access to hardware peripherals.  Intended only for hardware testing. Not for use by third-party applications."], 
	 "android.permission.NET_ADMIN" : ["signature", "Allows access to configure network interfaces, configure/use IPSec, etc."], 
	 "android.permission.REMOTE_AUDIO_PLAYBACK" : ["signature", "Allows registration for remote audio playback."], 
	 "android.permission.RECORD_AUDIO" : ["dangerous", "Used for permissions that are associated with accessing but are in a separate (more visible) permission group. Allows an application to record audio"], 
	 "android.permission.CAMERA" : ["dangerous", "Used for permissions that are associated with accessing camera or capturing images/video from the device. Required to be able to access the camera device. install on devices that don't support all camera features.</p>"], 
	 "android.permission.CAMERA_DISABLE_TRANSMIT_LED" : ["signature|system", "Allows disabling the transmit-indicator LED that is normally on when"], 
	 "android.permission.PROCESS_OUTGOING_CALLS" : ["dangerous", "Used for permissions that are associated with accessing and modifyign and modifying the phone state. Allows an application to monitor, modify, or abort outgoing calls."], 
	 "android.permission.MODIFY_PHONE_STATE" : ["signature|system", "Allows modification of the telephony state - power on, mmi, etc. Not for use by third-party applications."], 
	 "android.permission.READ_PHONE_STATE" : ["dangerous", "Allows read only access to phone state. targetSdkVersion}</a> is 4 or higher."], 
	 "android.permission.READ_PRECISE_PHONE_STATE" : ["dangerous", "Allows read only access to precise phone state.  Pending API council approval"], 
	 "android.permission.READ_PRIVILEGED_PHONE_STATE" : ["signature|system", "Allows read access to privileged phone state.  Used internally."], 
	 "android.permission.CALL_PHONE" : ["dangerous", "Allows an application to initiate a phone call without going through being placed."], 
	 "android.permission.USE_SIP" : ["dangerous", "Allows an application to use SIP service"], 
	 "android.permission.BIND_CALL_SERVICE" : ["system|signature", "Allows an application to request CallHandlerService implementations."], 
	 "android.permission.READ_EXTERNAL_STORAGE" : ["normal", "Group of permissions that are related to SD card access. Allows an application to read from external storage. targetSdkVersion}</a> is 4 or higher."], 
	 "android.permission.WRITE_EXTERNAL_STORAGE" : ["dangerous", "Allows an application to write to external storage. { android.content.Context#getExternalCacheDir}."], 
	 "android.permission.WRITE_MEDIA_STORAGE" : ["signature|system", "Allows an application to write to internal media storage"], 
	 "android.permission.MANAGE_DOCUMENTS" : ["signature|system", "Allows an application to manage access to documents, usually as part of a document picker."], 
	 "android.permission.DISABLE_KEYGUARD" : ["dangerous", "Group of permissions that are related to the screenlock. Allows applications to disable the keyguard"], 
	 "android.permission.GET_TASKS" : ["dangerous", "Group of permissions that are related to the other applications running apps, or killing background processes. Allows an application to get information about the currently or recently running tasks."], 
	 "android.permission.INTERACT_ACROSS_USERS" : ["signature|system|development", "Allows an application to call APIs that allow it to do interactions third party applications."], 
	 "android.permission.INTERACT_ACROSS_USERS_FULL" : ["signature", "Fuller form of { android.Manifest.permission#INTERACT_ACROSS_USERS} types of interactions."], 
	 "android.permission.MANAGE_USERS" : ["signature|system", "Allows an application to call APIs that allow it to query and manage third party applications."], 
	 "android.permission.GET_DETAILED_TASKS" : ["signature", "Allows an application to get full detailed information about"], 
	 "android.permission.REORDER_TASKS" : ["normal", "Allows an application to change the Z-order of tasks"], 
	 "android.permission.REMOVE_TASKS" : ["signature", "Allows an application to change to remove/kill tasks"], 
	 "android.permission.MANAGE_ACTIVITY_STACKS" : ["signature", "Allows an application to create/manage/remove stacks"], 
	 "android.permission.START_ANY_ACTIVITY" : ["signature", "Allows an application to start any activity, regardless of permission protection or exported state."], 
	 "android.permission.RESTART_PACKAGES" : ["normal", "The { android.app.ActivityManager#restartPackage} API is no longer supported."], 
	 "android.permission.KILL_BACKGROUND_PROCESSES" : ["normal", "Allows an application to call { android.app.ActivityManager#killBackgroundProcesses}."], 
	 "android.permission.SYSTEM_ALERT_WINDOW" : ["dangerous", "Group of permissions that allow manipulation of how another application displays UI to the user. Allows an application to open windows using the type system-level interaction with the user."], 
	 "android.permission.SET_WALLPAPER" : ["normal", "Group of permissions that allow manipulation of how another application displays UI to the user. Allows applications to set the wallpaper"], 
	 "android.permission.SET_WALLPAPER_HINTS" : ["normal", "Allows applications to set the wallpaper hints"], 
	 "android.permission.SET_TIME" : ["signature|system", "Group of permissions that are related to system clock. Allows applications to set the system time. Not for use by third-party applications."], 
	 "android.permission.SET_TIME_ZONE" : ["normal", "Allows applications to set the system time zone"], 
	 "android.permission.EXPAND_STATUS_BAR" : ["normal", "Used for permissions that change the status bar Allows an application to expand or collapse the status bar."], 
	 "com.android.launcher.permission.INSTALL_SHORTCUT" : ["dangerous", "None"], 
	 "com.android.launcher.permission.UNINSTALL_SHORTCUT" : ["dangerous", "None"], 
	 "android.permission.READ_SYNC_SETTINGS" : ["normal", "Used for permissions that access the sync settings or sync related information. Allows applications to read the sync settings"], 
	 "android.permission.WRITE_SYNC_SETTINGS" : ["normal", "Allows applications to write the sync settings"], 
	 "android.permission.READ_SYNC_STATS" : ["normal", "Allows applications to read the sync stats"], 
	 "android.permission.SET_SCREEN_COMPATIBILITY" : ["signature", "Group of permissions that are related to system APIs.  Many such as writing the global system settings.  Change the screen compatibility mode of applications"], 
	 "android.permission.ACCESS_ALL_EXTERNAL_STORAGE" : ["signature", "Allows an application to access all multi-user external storage"], 
	 "android.permission.CHANGE_CONFIGURATION" : ["signature|system|development", "Allows an application to modify the current configuration, such as locale."], 
	 "android.permission.WRITE_SETTINGS" : ["normal", "Allows an application to read or write the system settings."], 
	 "android.permission.WRITE_GSERVICES" : ["signature|system", "Allows an application to modify the Google service map. Not for use by third-party applications."], 
	 "android.permission.FORCE_STOP_PACKAGES" : ["signature", "Allows an application to call"], 
	 "android.permission.RETRIEVE_WINDOW_CONTENT" : ["signature|system", "Allows an application to retrieve the content of the active window An active window is the window that has fired an accessibility event."], 
	 "android.permission.SET_ANIMATION_SCALE" : ["signature|system|development", "Modify the global animation scaling factor. Not for use by third-party applications."], 
	 "android.permission.PERSISTENT_ACTIVITY" : ["normal", "This functionality will be removed in the future; please do not use. Allow an application to make its activities persistent."], 
	 "android.permission.GET_PACKAGE_SIZE" : ["normal", "Allows an application to find out the space used by any package."], 
	 "android.permission.SET_PREFERRED_APPLICATIONS" : ["signature", "No longer useful, see for details."], 
	 "android.permission.RECEIVE_BOOT_COMPLETED" : ["normal", "Allows an application to receive the to the user."], 
	 "android.permission.BROADCAST_STICKY" : ["normal", "Allows an application to broadcast sticky intents.  These are to wait for the next broadcast."], 
	 "android.permission.MOUNT_UNMOUNT_FILESYSTEMS" : ["system|signature", "Allows mounting and unmounting file systems for removable storage. Not for use by third-party applications."], 
	 "android.permission.MOUNT_FORMAT_FILESYSTEMS" : ["system|signature", "Allows formatting file systems for removable storage. Not for use by third-party applications."], 
	 "android.permission.ASEC_ACCESS" : ["signature", "Allows access to ASEC non-destructive API calls"], 
	 "android.permission.ASEC_CREATE" : ["signature", "Allows creation of ASEC volumes"], 
	 "android.permission.ASEC_DESTROY" : ["signature", "Allows destruction of ASEC volumes"], 
	 "android.permission.ASEC_MOUNT_UNMOUNT" : ["signature", "Allows mount / unmount of ASEC volumes"], 
	 "android.permission.ASEC_RENAME" : ["signature", "Allows rename of ASEC volumes"], 
	 "android.permission.WRITE_APN_SETTINGS" : ["signature|system", "Allows applications to write the apn settings. Not for use by third-party applications."], 
	 "android.permission.SUBSCRIBED_FEEDS_READ" : ["normal", "Allows an application to allow access the subscribed feeds ContentProvider."], 
	 "android.permission.SUBSCRIBED_FEEDS_WRITE" : ["dangerous", ""], 
	 "android.permission.CHANGE_NETWORK_STATE" : ["normal", "Allows applications to change network connectivity state"], 
	 "android.permission.CLEAR_APP_CACHE" : ["dangerous", "Allows an application to clear the caches of all installed applications on the device."], 
	 "android.permission.ALLOW_ANY_CODEC_FOR_PLAYBACK" : ["signature|system", "Allows an application to use any media decoder when decoding for playback"], 
	 "android.permission.MANAGE_CA_CERTIFICATES" : ["signature|system", "Allows an application to install and/or uninstall CA certificates on"], 
	 "android.permission.WRITE_SECURE_SETTINGS" : ["signature|system|development", "Group of permissions that are related to development features.  These purposes. Allows an application to read or write the secure system settings. Not for use by third-party applications."], 
	 "android.permission.DUMP" : ["signature|system|development", "Allows an application to retrieve state dump information from system services. Not for use by third-party applications."], 
	 "android.permission.READ_LOGS" : ["signature|system|development", "Allows an application to read the low-level system log files. Log entries can contain the user's private information."], 
	 "android.permission.SET_DEBUG_APP" : ["signature|system|development", "Configure an application for debugging. Not for use by third-party applications."], 
	 "android.permission.SET_PROCESS_LIMIT" : ["signature|system|development", "Allows an application to set the maximum number of (not needed) Not for use by third-party applications."], 
	 "android.permission.SET_ALWAYS_FINISH" : ["signature|system|development", "Allows an application to control whether activities are immediately Not for use by third-party applications."], 
	 "android.permission.SIGNAL_PERSISTENT_PROCESSES" : ["signature|system|development", "Allow an application to request that a signal be sent to all persistent processes. Not for use by third-party applications."], 
	 "android.permission.DIAGNOSTIC" : ["signature", "Allows applications to RW to diagnostic resources. Not for use by third-party applications."], 
	 "android.permission.STATUS_BAR" : ["signature|system", "Allows an application to open, close, or disable the status bar Not for use by third-party applications."], 
	 "android.permission.STATUS_BAR_SERVICE" : ["signature", "Allows an application to be the status bar.  Currently used only by SystemUI.apk"], 
	 "android.permission.FORCE_BACK" : ["signature", "Allows an application to force a BACK operation on whatever is the Not for use by third-party applications."], 
	 "android.permission.UPDATE_DEVICE_STATS" : ["signature|system", "Allows an application to update device statistics. Not for use by third-party applications."], 
	 "android.permission.GET_APP_OPS_STATS" : ["signature|system|development", "Allows an application to collect battery statistics"], 
	 "android.permission.UPDATE_APP_OPS_STATS" : ["signature|system", "Allows an application to update application operation statistics. Not for use by third party apps."], 
	 "android.permission.INTERNAL_SYSTEM_WINDOW" : ["signature", "Allows an application to open windows that are for use by parts Not for use by third-party applications."], 
	 "android.permission.MANAGE_APP_TOKENS" : ["signature", "Allows an application to manage (create, destroy, Not for use by third-party applications."], 
	 "android.permission.FREEZE_SCREEN" : ["signature", "Allows the application to temporarily freeze the screen for a full-screen transition."], 
	 "android.permission.INJECT_EVENTS" : ["signature", "Allows an application to inject user events (keys, touch, trackball) Not for use by third-party applications."], 
	 "android.permission.FILTER_EVENTS" : ["signature", "Allows an application to register an input filter which filters the stream of user events (keys, touch, trackball) before they are dispatched to any window."], 
	 "android.permission.RETRIEVE_WINDOW_INFO" : ["signature", "Allows an application to retrieve info for a window from the window manager."], 
	 "android.permission.TEMPORARY_ENABLE_ACCESSIBILITY" : ["signature", "Allows an application to temporary enable accessibility on the device."], 
	 "android.permission.MAGNIFY_DISPLAY" : ["signature", "Allows an application to magnify the content of a display."], 
	 "android.permission.SET_ACTIVITY_WATCHER" : ["signature", "Allows an application to watch and control how activities are Not for use by third-party applications."], 
	 "android.permission.SHUTDOWN" : ["signature|system", "Allows an application to call the activity manager shutdown() API"], 
	 "android.permission.STOP_APP_SWITCHES" : ["signature|system", "Allows an application to tell the activity manager to temporarily"], 
	 "android.permission.GET_TOP_ACTIVITY_INFO" : ["signature", "Allows an application to retrieve private information about Not for use by third-party applications."], 
	 "android.permission.READ_INPUT_STATE" : ["signature", "Allows an application to retrieve the current state of keys and  The API that used this permission has been removed."], 
	 "android.permission.BIND_INPUT_METHOD" : ["signature", "Must be required by an { android.inputmethodservice.InputMethodService}, to ensure that only the system can bind to it."], 
	 "android.permission.BIND_ACCESSIBILITY_SERVICE" : ["signature", "Must be required by an { android.accessibilityservice.AccessibilityService}, to ensure that only the system can bind to it."], 
	 "android.permission.BIND_PRINT_SERVICE" : ["signature", "Must be required by a { android.printservice.PrintService}, to ensure that only the system can bind to it."], 
	 "android.permission.BIND_NFC_SERVICE" : ["signature", "Must be required by a { android.nfc.cardemulation.HostApduService} the system can bind to it."], 
	 "android.permission.BIND_PRINT_SPOOLER_SERVICE" : ["signature", "Must be required by the PrintSpooler to ensure that only the system can bind to it."], 
	 "android.permission.BIND_TEXT_SERVICE" : ["signature", "Must be required by a TextService (e.g. SpellCheckerService) to ensure that only the system can bind to it."], 
	 "android.permission.BIND_VPN_SERVICE" : ["signature", "Must be required by a { android.net.VpnService}, to ensure that only the system can bind to it."], 
	 "android.permission.BIND_WALLPAPER" : ["signature|system", "Must be required by a { android.service.wallpaper.WallpaperService}, to ensure that only the system can bind to it."], 
	 "android.permission.BIND_REMOTE_DISPLAY" : ["signature", "Must be required by a { com.android.media.remotedisplay.RemoteDisplayProvider},"], 
	 "android.permission.BIND_DEVICE_ADMIN" : ["signature", "Must be required by device administration receiver, to ensure that only the system can interact with it."], 
	 "android.permission.MANAGE_DEVICE_ADMINS" : ["signature|system", "Required to add or remove another application as a device admin."], 
	 "android.permission.SET_ORIENTATION" : ["signature", "Allows low-level access to setting the orientation (actually Not for use by third-party applications."], 
	 "android.permission.SET_POINTER_SPEED" : ["signature", "Allows low-level access to setting the pointer speed. Not for use by third-party applications."], 
	 "android.permission.SET_KEYBOARD_LAYOUT" : ["signature", "Allows low-level access to setting the keyboard layout."], 
	 "android.permission.INSTALL_PACKAGES" : ["signature|system", "Allows an application to install packages. Not for use by third-party applications."], 
	 "android.permission.CLEAR_APP_USER_DATA" : ["signature", "Allows an application to clear user data. Not for use by third-party applications."], 
	 "android.permission.DELETE_CACHE_FILES" : ["signature|system", "Allows an application to delete cache files. Not for use by third-party applications."], 
	 "android.permission.DELETE_PACKAGES" : ["signature|system", "Allows an application to delete packages. Not for use by third-party applications."], 
	 "android.permission.MOVE_PACKAGE" : ["signature|system", "Allows an application to move location of installed package."], 
	 "android.permission.CHANGE_COMPONENT_ENABLED_STATE" : ["signature|system", "Allows an application to change whether an application component (other than its own) is Not for use by third-party applications."], 
	 "android.permission.GRANT_REVOKE_PERMISSIONS" : ["signature", "Allows an application to grant or revoke specific permissions."], 
	 "android.permission.ACCESS_SURFACE_FLINGER" : ["signature", "Allows an application to use SurfaceFlinger's low level features. Not for use by third-party applications."], 
	 "android.permission.READ_FRAME_BUFFER" : ["signature|system", "Allows an application to take screen shots and more generally Not for use by third-party applications."], 
	 "android.permission.CONFIGURE_WIFI_DISPLAY" : ["signature", "Allows an application to configure and connect to Wifi displays"], 
	 "android.permission.CONTROL_WIFI_DISPLAY" : ["signature", "Allows an application to control low-level features of Wifi displays"], 
	 "android.permission.CAPTURE_AUDIO_OUTPUT" : ["signature|system", "Allows an application to capture audio output. Not for use by third-party applications.</p>"], 
	 "android.permission.CAPTURE_AUDIO_HOTWORD" : ["signature|system", "Allows an application to capture audio for hotword detection."], 
	 "android.permission.CAPTURE_VIDEO_OUTPUT" : ["signature|system", "Allows an application to capture video output. Not for use by third-party applications.</p>"], 
	 "android.permission.CAPTURE_SECURE_VIDEO_OUTPUT" : ["signature|system", "Allows an application to capture secure video output. Not for use by third-party applications.</p>"], 
	 "android.permission.MEDIA_CONTENT_CONTROL" : ["signature|system", "Allows an application to know what content is playing and control its playback. Not for use by third-party applications due to privacy of media consumption</p>"], 
	 "android.permission.BRICK" : ["signature", "Required to be able to disable the device (very dangerous!). Not for use by third-party applications.."], 
	 "android.permission.REBOOT" : ["signature|system", "Required to be able to reboot the device. Not for use by third-party applications."], 
	 "android.permission.DEVICE_POWER" : ["signature", "Allows low-level access to power management. Not for use by third-party applications."], 
	 "android.permission.NET_TUNNELING" : ["signature", "Allows low-level access to tun tap driver"], 
	 "android.permission.FACTORY_TEST" : ["signature", "Run as a manufacturer test application, running as the root user. Not for use by third-party applications."], 
	 "android.permission.BROADCAST_PACKAGE_REMOVED" : ["signature", "Allows an application to broadcast a notification that an application Not for use by third-party applications."], 
	 "android.permission.BROADCAST_SMS" : ["signature", "Allows an application to broadcast an SMS receipt notification. Not for use by third-party applications."], 
	 "android.permission.BROADCAST_WAP_PUSH" : ["signature", "Allows an application to broadcast a WAP PUSH receipt notification. Not for use by third-party applications."], 
	 "android.permission.MASTER_CLEAR" : ["signature|system", "Not for use by third-party applications."], 
	 "android.permission.CALL_PRIVILEGED" : ["signature|system", "Allows an application to call any phone number, including emergency Not for use by third-party applications."], 
	 "android.permission.PERFORM_CDMA_PROVISIONING" : ["signature|system", "Allows an application to perform CDMA OTA provisioning"], 
	 "android.permission.CONTROL_LOCATION_UPDATES" : ["signature|system", "Allows enabling/disabling location update notifications from Not for use by third-party applications."], 
	 "android.permission.ACCESS_CHECKIN_PROPERTIES" : ["signature|system", "Allows read/write access to the 'properties' table in the checkin Not for use by third-party applications."], 
	 "android.permission.PACKAGE_USAGE_STATS" : ["signature|system", "Allows an application to collect component usage statistics"], 
	 "android.permission.BATTERY_STATS" : ["signature|system", "Allows an application to collect battery statistics"], 
	 "android.permission.BACKUP" : ["signature|system", "Allows an application to control the backup and restore process.  pending API council"], 
	 "android.permission.CONFIRM_FULL_BACKUP" : ["signature", "Allows a package to launch the secure full-backup confirmation UI."], 
	 "android.permission.BIND_REMOTEVIEWS" : ["signature|system", "Must be required by a { android.widget.RemoteViewsService}, to ensure that only the system can bind to it."], 
	 "android.permission.BIND_APPWIDGET" : ["signature|system", "Allows an application to tell the AppWidget service which application Not for use by third-party applications."], 
	 "android.permission.BIND_KEYGUARD_APPWIDGET" : ["signature|system", "Private permission, to restrict who can bring up a dialog to add a new"], 
	 "android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS" : ["signature|system", "Internal permission allowing an application to query/set which"], 
	 "android.permission.CHANGE_BACKGROUND_DATA_SETTING" : ["signature", "Allows applications to change the background data setting.  pending API council"], 
	 "android.permission.GLOBAL_SEARCH" : ["signature|system", "This permission can be used on content providers to allow the global besides global search."], 
	 "android.permission.GLOBAL_SEARCH_CONTROL" : ["signature", "Internal permission protecting access to the global search"], 
	 "android.permission.SET_WALLPAPER_COMPONENT" : ["signature|system", "Allows applications to set a live wallpaper. own apk as Ghod Intended."], 
	 "android.permission.READ_DREAM_STATE" : ["signature", "Allows applications to read dream settings and dream state."], 
	 "android.permission.WRITE_DREAM_STATE" : ["signature", "Allows applications to write dream settings, and start or stop dreaming."], 
	 "android.permission.ACCESS_CACHE_FILESYSTEM" : ["signature|system", "Allow an application to read and write the cache partition."], 
	 "android.permission.COPY_PROTECTED_DATA" : ["signature", "Must be required by default container service so that only"], 
	 "android.permission.CRYPT_KEEPER" : ["signature|system", "Internal permission protecting access to the encryption methods"], 
	 "android.permission.READ_NETWORK_USAGE_HISTORY" : ["signature|system", "Allows an application to read historical network usage for specific networks and applications."], 
	 "android.permission.MANAGE_NETWORK_POLICY" : ["signature", "Allows an application to manage network policies (such as warning and disable limits) and to define application-specific rules."], 
	 "android.permission.MODIFY_NETWORK_ACCOUNTING" : ["signature|system", "Allows an application to account its network traffic against other UIDs. Used third party apps."], 
	 "android.permission.MARK_NETWORK_SOCKET" : ["signature|system", "Allows an application to mark traffic as from another user for per user routing."], 
	 "android.intent.category.MASTER_CLEAR.permission.C2D_MESSAGE" : ["signature", "C2DM permission."], 
	 "android.permission.PACKAGE_VERIFICATION_AGENT" : ["signature|system", "Package verifier needs to have this permission before the PackageManager will"], 
	 "android.permission.BIND_PACKAGE_VERIFIER" : ["signature", "Must be required by package verifier receiver, to ensure that only the"], 
	 "android.permission.SERIAL_PORT" : ["signature|system", "Allows applications to access serial ports via the SerialManager."], 
	 "android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY" : ["signature", "Allows the holder to access content providers from outside an ApplicationThread."], 
	 "android.permission.UPDATE_LOCK" : ["signatureOrSystem", "Allows an application to hold an UpdateLock, recommending that a headless"], 
	 "android.permission.ACCESS_NOTIFICATIONS" : ["signature|system", "Allows an application to read the current set of notifications, including"], 
	 "android.permission.ACCESS_KEYGUARD_SECURE_STORAGE" : ["signature", "Allows access to keyguard secure storage.  Only allowed for system processes."], 
	 "android.permission.CONTROL_KEYGUARD" : ["signature", "Allows an application to control keyguard.  Only allowed for system processes."], 
	 "android.permission.BIND_NOTIFICATION_LISTENER_SERVICE" : ["signature", "Must be required by an { to ensure that only the system can bind to it."], 
	 "android.permission.INVOKE_CARRIER_SETUP" : ["signature|system", "Allows an application to call into a carrier setup flow. It is up to the  This is not a third-party API (intended for OEMs and system apps)."], 
	 "android.permission.ACCESS_NETWORK_CONDITIONS" : ["signature|system", "Allows an application to listen for network condition observations.  This is not a third-party API (intended for system apps)."], 
	 }